name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: test
      run: pwd
    - name: test3
      run: ls
    - name: test2
      run: ls /app/build/outputs/apk/release
    - name: run App Center Distribute
      uses: wzieba/AppCenter-Github-Action@v1
      with:
        appName: first-flight/appcenter-sample
        token: ${{secrets.APP_CENTER_TOKEN}}
        group: Collaborators
        file: app/build/outputs/apk/release/app-release.apk
        notifyTesters: false
        debug: false
