name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: run App Center Distribute
      uses: joabalea/App-Center-action@v1.0.2
      with:
        command: appcenter distribute groups publish --app first-flight/appcenter-sample --file app/build/outputs/apk/release/app-release.apk --group "Collaborators"
        token: ${{secrets.APP_CENTER_TOKEN}}
